import { DBInterface } from "../interfaces";

export async function migrateV19(tx: DBInterface["tx"] extends (fn: (tx: infer T) => any) => any ? T : never) {

  // VERSION: 19
  await tx.exec(`PRAGMA user_version = 19`);

  // Add summary and diagram fields to scripts table for Spec 12 - Explain Automation.
  // - summary: One-sentence description of what the automation does
  // - diagram: Mermaid diagram source showing the automation flow
  // These are generated by the agent when saving a script and displayed on the
  // workflow detail page for user understanding.
  await tx.exec(`SELECT crsql_begin_alter('scripts')`);
  await tx.exec(`ALTER TABLE scripts ADD COLUMN summary text not null default ''`);
  await tx.exec(`ALTER TABLE scripts ADD COLUMN diagram text not null default ''`);
  await tx.exec(`SELECT crsql_commit_alter('scripts')`);
}
