import { z } from "zod";
import { tool } from "ai";
import { FileStore, type File } from "@app/db";
import { EvalContext } from "../sandbox/sandbox";
import { getEnv } from "../env";
import { createHash } from "crypto";
import { fileUtils } from "@app/node";
import { detectBufferMime, mimeToExt } from "@app/node";
import fs from "fs";
import debug from "debug";

const debugImg = debug("ImagesGenerate");

export function makeImagesGenerateTool(
  fileStore: FileStore,
  userPath: string | undefined,
  getContext: () => EvalContext
) {
  return tool({
    description: `Generate images using AI image generation model.
Takes a textual prompt describing the desired image and an optional aspect ratio.
Generates images and saves them to files. Returns information about the generated image files.`,
    inputSchema: z.object({
      prompt: z
        .string()
        .min(1)
        .max(1000)
        .describe("Textual description of the image to generate"),
      file_prefix: z
        .string()
        .min(1)
        .max(50)
        .describe(
          "Prefix to use for the filename of generated images, no spaces, filename-suitable symbols only"
        ),
      aspect_ratio: z
        .string()
        .optional()
        .nullable()
        .describe(
          "Aspect ratio for the image (e.g., '16:9', '1:1', '4:3'). Defaults to '1:1' if not specified"
        ),
    }),
    outputSchema: z.object({
      images: z
        .array(
          z.object({
            id: z.string().describe("File ID of the generated image"),
            name: z.string().describe("Filename of the generated image"),
            path: z.string().describe("Local file path"),
            size: z.number().describe("File size in bytes"),
            media_type: z.string().describe("MIME type of the image"),
            summary: z.string().describe("Summary/description of the image"),
            upload_time: z.string().describe("Generation timestamp"),
          })
        )
        .describe("Array of generated image file records"),
      reasoning: z.string().describe("Image model's reasoning"),
    }),
    execute: async (input) => {
      const { prompt, file_prefix, aspect_ratio = "1:1" } = input;

      if (!userPath) {
        throw new Error("User path not configured");
      }

      // Get environment variables
      const env = getEnv();
      if (!env.OPENROUTER_API_KEY?.trim()) {
        throw new Error("OpenRouter API key not configured");
      }

      const imageModel = env.IMAGE_MODEL || "google/gemini-3-pro-image-preview";

      try {
        debugImg(`Generating image ${aspect_ratio}, prompt: ${prompt}`);
        // Call OpenRouter API for image generation
        const response = await fetch(
          "https://openrouter.ai/api/v1/chat/completions",
          {
            method: "POST",
            headers: {
              Authorization: `Bearer ${env.OPENROUTER_API_KEY}`,
              "Content-Type": "application/json",
            },
            body: JSON.stringify({
              model: imageModel,
              messages: [
                {
                  role: "user",
                  content: prompt,
                },
              ],
              modalities: ["image", "text"],
              image_config: {
                aspect_ratio: aspect_ratio,
              },
              usage: {
                include: true,
              },
            }),
          }
        );

        if (!response.ok) {
          const errorText = await response.text();
          throw new Error(
            `OpenRouter API error: ${response.status} - ${errorText}`
          );
        }

        const result = await response.json();

        if (!result.choices || result.choices.length === 0) {
          throw new Error("No image generated by the model");
        }

        const usage = result.usage || {};
        const message = result.choices[0].message;
        const reasoning: string = message.reasoning;
        debugImg("Generated images reasoning", reasoning, "usage", usage);

        if (!message.images || message.images.length === 0) {
          throw new Error("No images found in the response");
        }
        debugImg("Generated images", message.images);

        const generatedFiles: File[] = [];

        // Process each generated image
        for (let index = 0; index < message.images.length; index++) {
          const image = message.images[index];
          const imageUrl = image.image_url.url;

          // Download the image from the URL
          const imageResponse = await fetch(imageUrl);
          if (!imageResponse.ok) {
            throw new Error(
              `Failed to download image ${index + 1}: ${imageResponse.status}`
            );
          }

          const imageBuffer = Buffer.from(await imageResponse.arrayBuffer());

          // Calculate SHA256 hash as ID
          const hash = createHash("sha256");
          hash.update(imageBuffer);
          const fileId = hash.digest("hex");

          // Check if file already exists (unlikely for generated images, but good practice)
          const existingFile = await fileStore.getFile(fileId);
          if (existingFile) {
            generatedFiles.push(existingFile);
            continue;
          }

          // Detect media type
          let mediaType = await detectBufferMime(imageBuffer);
          if (!mediaType) {
            // Default to PNG for generated images
            mediaType = "image/png";
          }

          // Get file extension
          const extension = mimeToExt(mediaType) || "png";

          // Generate filename
          const timestamp = new Date().toISOString().replace(/[:.T]/g, "-");
          const filename = `${file_prefix}-${timestamp}-${
            index + 1
          }.${extension}`;

          // Ensure files directory exists
          const filesDir = fileUtils.join(userPath, "files");
          if (!fileUtils.existsSync(filesDir)) {
            fs.mkdirSync(filesDir, { recursive: true });
          }

          // Create local file path
          const fileNameLocal = `${fileId}.${extension}`;
          const filePathLocal = fileUtils.join(filesDir, fileNameLocal);

          // Write file to disk
          fs.writeFileSync(filePathLocal, imageBuffer);

          // Create summary with prompt
          const summary = `Generated by user request, prompt: ${prompt}`;

          // Create file record
          const fileRecord: File = {
            id: fileId,
            name: filename,
            path: fileNameLocal,
            size: imageBuffer.length,
            summary: summary,
            upload_time: new Date().toISOString(),
            media_type: mediaType,
          };

          // Insert file to database
          await fileStore.insertFile(fileRecord);
          generatedFiles.push(fileRecord);
        }

        // Create event for tracking
        await getContext().createEvent("images_generate", {
          prompt,
          aspect_ratio,
          count: generatedFiles.length,
          files: generatedFiles.map((f) => f.path),
          usage: { cost: usage.cost },
        });

        return {
          images: generatedFiles,
          reasoning,
        };
      } catch (error) {
        throw new Error(
          `Image generation failed: ${
            error instanceof Error ? error.message : "Unknown error"
          }`
        );
      }
    },
  });
}
