import { z } from "zod";
import { tool } from "ai";
import { EvalContext } from "../sandbox/sandbox";
import { getEnv } from "../env";
import { getModelName } from "../model";
import debug from "debug";

const debugTextSummarize = debug("TextSummarize");

export function makeTextSummarizeTool(getContext: () => EvalContext) {
  return tool({
    description: `Summarize text to a specified maximum length using AI.
Takes input text and optional maximum character count, returns a concise summary.
Uses temperature 0 and no reasoning for straightforward summarization.`,
    inputSchema: z.object({
      text: z
        .string()
        .min(1)
        .describe("Input text to summarize"),
      max_chars: z
        .number()
        .min(100)
        .max(10000)
        .default(1500)
        .optional()
        .describe("Maximum number of characters in the summary (default: 1500)"),
    }),
    outputSchema: z.object({
      summary: z.string().describe("Summarized text"),
    }),
    execute: async (input) => {
      const { text, max_chars = 1500 } = input;

      const env = getEnv();
      if (!env.OPENROUTER_API_KEY?.trim()) {
        throw new Error("OpenRouter API key not configured");
      }

      const model = getModelName();
      const baseURL = env.OPENROUTER_BASE_URL || "https://openrouter.ai/api/v1";

      debugTextSummarize(`Summarizing text (${text.length} chars) to max ${max_chars} chars`);

      const prompt = `Summarize the following text in approximately ${max_chars} characters or less. Provide a clear, concise summary that captures the key points.

Text to summarize:
${text}`;

      try {
        const response = await fetch(`${baseURL}/chat/completions`, {
          method: "POST",
          headers: {
            Authorization: `Bearer ${env.OPENROUTER_API_KEY}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            model,
            messages: [
              {
                role: "user",
                content: prompt,
              },
            ],
            temperature: 0,
            max_tokens: Math.ceil(max_chars / 2), // Rough estimate: ~2 chars per token
          }),
        });

        if (!response.ok) {
          const errorText = await response.text();
          throw new Error(`OpenRouter API error: ${response.status} - ${errorText}`);
        }

        const result = await response.json();

        if (!result.choices || result.choices.length === 0) {
          throw new Error("No response generated by the model");
        }

        const content = result.choices[0].message?.content?.trim();
        if (!content) {
          throw new Error("No content found in the response");
        }

        debugTextSummarize("Summarization completed", { 
          inputLength: text.length,
          summaryLength: content.length 
        });

        await getContext().createEvent("text_summarize", {
          inputLength: text.length,
          summaryLength: content.length,
          maxChars: max_chars
        });

        return { summary: content };
      } catch (error) {
        throw new Error(`Text summarization failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
      }
    },
  });
}
