import { z } from "zod";
import { tool } from "ai";
import { EvalContext } from "../sandbox/sandbox";
import { getEnv } from "../env";
import { getModelName } from "../model";
import debug from "debug";

const debugTextRoute = debug("TextRoute");

export function makeTextRouteTool(getContext: () => EvalContext) {
  return tool({
    description: `Route text to one of several options based on its content using AI.
Takes input text and a list of possible routes (each with id and description), and returns the most appropriate route id.
Uses temperature 0 and light reasoning for consistent routing decisions.`,
    inputSchema: z.object({
      text: z
        .string()
        .min(1)
        .describe("Input text to analyze for routing"),
      routes: z
        .array(
          z.object({
            id: z.string().describe("Route identifier"),
            description: z.string().describe("Description of when this route should be selected"),
          })
        )
        .min(1)
        .describe("List of possible routes to choose from"),
    }),
    outputSchema: z.object({
      route_id: z.string().describe("ID of the selected route"),
    }),
    execute: async (input) => {
      const { text, routes } = input;

      const env = getEnv();
      if (!env.OPENROUTER_API_KEY?.trim()) {
        throw new Error("OpenRouter API key not configured");
      }

      const model = getModelName();
      const baseURL = env.OPENROUTER_BASE_URL || "https://openrouter.ai/api/v1";

      debugTextRoute(`Routing text (${text.length} chars) with ${routes.length} options`);

      const routesList = routes
        .map((r) => `- ${r.id}: ${r.description}`)
        .join("\n");

      const prompt = `You are a routing classifier. Based on the input text, select the most appropriate route from the options below.

Available routes:
${routesList}

Input text:
${text}

Return ONLY the route id, nothing else.`;

      try {
        const response = await fetch(`${baseURL}/chat/completions`, {
          method: "POST",
          headers: {
            Authorization: `Bearer ${env.OPENROUTER_API_KEY}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            model,
            messages: [
              {
                role: "user",
                content: prompt,
              },
            ],
            temperature: 0,
            reasoning_effort: "low",
            usage: {
              include: true,
            },
          }),
        });

        if (!response.ok) {
          const errorText = await response.text();
          throw new Error(`OpenRouter API error: ${response.status} - ${errorText}`);
        }

        const result = await response.json();

        if (!result.choices || result.choices.length === 0) {
          throw new Error("No response generated by the model");
        }

        const usage = result.usage || {};
        const content = result.choices[0].message?.content?.trim();
        if (!content) {
          throw new Error("No content found in the response");
        }

        debugTextRoute("Routing completed", { selectedRoute: content }, "usage", usage);

        await getContext().createEvent("text_route", {
          textLength: text.length,
          routeCount: routes.length,
          selectedRoute: content,
          usage: { cost: usage.cost },
        });

        return { route_id: content };
      } catch (error) {
        throw new Error(`Text routing failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
      }
    },
  });
}
