import { z } from "zod";
import { tool } from "ai";
import { EvalContext } from "../sandbox/sandbox";
import { getEnv } from "../env";
import { getModelName } from "../model";
import debug from "debug";

const debugTextExtract = debug("TextExtract");

export function makeTextExtractTool(getContext: () => EvalContext) {
  return tool({
    description: `Extract structured data from text according to a JSON schema using AI.
Takes input text and a JSON schema, and returns the extracted data in JSON format.
Uses temperature 0 and light reasoning for reliable parsing.`,
    inputSchema: z.object({
      text: z.string().min(1).describe("Input text to extract data from"),
      json_schema: z
        .any()
        .describe(
          "JSON schema object describing the expected output structure"
        ),
    }),
    outputSchema: z.object({
      result: z.any().describe("Extracted object matching the json_schema"),
    }),
    execute: async (input) => {
      const { text, json_schema } = input;

      if (!json_schema) throw new Error("No json_schema specified");

      // OpenRouter's docs say this is required
      json_schema["strict"] = true;

      const env = getEnv();
      if (!env.OPENROUTER_API_KEY?.trim()) {
        throw new Error("OpenRouter API key not configured");
      }

      const model = getModelName();
      const baseURL = env.OPENROUTER_BASE_URL || "https://openrouter.ai/api/v1";

      debugTextExtract(
        `Extracting from text (${text.length} chars) with schema`
      );

      const prompt = `Extract information from the following text and output it in JSON format according to the schema provided.

JSON Schema:
${JSON.stringify(json_schema)}

Text to extract from:
${text}

Output only valid JSON matching the schema, no additional text or markdown formatting.`;

      try {
        const response = await fetch(`${baseURL}/chat/completions`, {
          method: "POST",
          headers: {
            Authorization: `Bearer ${env.OPENROUTER_API_KEY}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            model,
            messages: [
              {
                role: "user",
                content: prompt,
              },
            ],
            temperature: 0,
            reasoning_effort: "low",
            response_format: { type: "json_schema", json_schema },
            usage: {
              include: true,
            },
          }),
        });

        if (!response.ok) {
          const errorText = await response.text();
          throw new Error(
            `OpenRouter API error: ${response.status} - ${errorText}`
          );
        }

        const result = await response.json();

        if (!result.choices || result.choices.length === 0) {
          throw new Error("No response generated by the model");
        }

        const usage = result.usage || {};
        let content = result.choices[0].message?.content as string;
        if (!content) {
          throw new Error("No content found in the response");
        }

        debugTextExtract("Extraction completed", content, "usage", usage);

        // Cut markdown just to make sure
        content = content.trim();
        if (content.startsWith("```json"))
          content = content.substring("```json".length);
        if (content.endsWith("```"))
          content = content.substring(0, content.length - "```".length);
        content = content.trim();

        try {
          const data = JSON.parse(content);
          await getContext().createEvent("text_extract", {
            inputLength: text.length,
            output: data,
            usage: { cost: usage.cost }
          });

          return { result: data };
        } catch (jsError) {
          debugTextExtract("Failed to parse", content, jsError);
          // Pass the content to the caller for them to figure it out
          throw "Error parsing reply: " + content;
        }
      } catch (error) {
        throw new Error(
          `Text extraction failed: ${
            error instanceof Error ? error.message : error
          }`
        );
      }
    },
  });
}
