import { z } from "zod";
import { tool } from "ai";
import { EvalContext } from "../sandbox/sandbox";
import { getEnv } from "../env";
import { getModelName } from "../model";
import debug from "debug";

const debugTextGenerate = debug("TextGenerate");

export function makeTextGenerateTool(getContext: () => EvalContext) {
  return tool({
    description: `Generate text based on a prompt using AI.
Takes a prompt and optional temperature/max_chars parameters, returns generated text.
Temperature controls randomness (0=deterministic, 1=very random), default 0.3.`,
    inputSchema: z.object({
      prompt: z
        .string()
        .min(1)
        .describe("Prompt to generate text from"),
      temperature: z
        .number()
        .min(0)
        .max(1)
        .default(0.3)
        .optional()
        .describe("Sampling temperature: 0 is deterministic, 1 is very random (default: 0.3)"),
      max_chars: z
        .number()
        .min(100)
        .max(10000)
        .default(1500)
        .optional()
        .describe("Maximum number of characters to generate (default: 1500)"),
    }),
    outputSchema: z.object({
      text: z.string().describe("Generated text"),
    }),
    execute: async (input) => {
      const { prompt, temperature = 0.3, max_chars = 1500 } = input;

      const env = getEnv();
      if (!env.OPENROUTER_API_KEY?.trim()) {
        throw new Error("OpenRouter API key not configured");
      }

      const model = getModelName();
      const baseURL = env.OPENROUTER_BASE_URL || "https://openrouter.ai/api/v1";

      debugTextGenerate(`Generating text with temperature ${temperature}, max ${max_chars} chars`);

      try {
        const response = await fetch(`${baseURL}/chat/completions`, {
          method: "POST",
          headers: {
            Authorization: `Bearer ${env.OPENROUTER_API_KEY}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            model,
            messages: [
              {
                role: "user",
                content: prompt,
              },
            ],
            temperature,
            max_tokens: Math.ceil(max_chars / 2), // Rough estimate: ~2 chars per token
            usage: {
              include: true,
            },
          }),
        });

        if (!response.ok) {
          const errorText = await response.text();
          throw new Error(`OpenRouter API error: ${response.status} - ${errorText}`);
        }

        const result = await response.json();

        if (!result.choices || result.choices.length === 0) {
          throw new Error("No response generated by the model");
        }

        const usage = result.usage || {};
        const content = result.choices[0].message?.content?.trim();
        if (!content) {
          throw new Error("No content found in the response");
        }

        debugTextGenerate("Generation completed", {
          promptLength: prompt.length,
          generatedLength: content.length
        }, "usage", usage);

        await getContext().createEvent("text_generate", {
          promptLength: prompt.length,
          generatedLength: content.length,
          temperature,
          maxChars: max_chars,
          usage: { cost: usage.cost },
        });

        return { text: content };
      } catch (error) {
        throw new Error(`Text generation failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
      }
    },
  });
}
