import { z } from "zod";
import { tool } from "ai";
import { EvalContext } from "../sandbox/sandbox";
import { getEnv } from "../env";
import { getTextModelName } from "../model";
import debug from "debug";
import { AuthError, LogicError, NetworkError, classifyHttpError, classifyGenericError, isClassifiedError } from "../errors";

const debugTextClassify = debug("TextClassify");

export function makeTextClassifyTool(getContext: () => EvalContext) {
  return tool({
    description: `Classify text into one of several classes based on its content using AI.
Takes input text and a list of possible classes (each with id and description), and returns the most appropriate class id.
Uses temperature 0 and light reasoning for consistent classification decisions.`,
    inputSchema: z.object({
      text: z
        .string()
        .min(1)
        .describe("Input text to analyze for classification"),
      classes: z
        .array(
          z.object({
            id: z.string().describe("Class identifier"),
            description: z
              .string()
              .describe("Description of when this class should be selected"),
          })
        )
        .min(1)
        .describe("List of possible classes to choose from"),
    }),
    outputSchema: z.object({
      class_id: z.string().describe("ID of the selected class"),
    }),
    execute: async (input) => {
      const { text, classes } = input;

      const env = getEnv();
      if (!env.OPENROUTER_API_KEY?.trim()) {
        throw new AuthError("OpenRouter API key not configured", { source: "Text.classify" });
      }

      const model = getTextModelName();
      const baseURL = env.OPENROUTER_BASE_URL || "https://openrouter.ai/api/v1";

      debugTextClassify(
        `Classifying text (${text.length} chars) with ${classes.length} options`
      );

      const classesList = classes
        .map((c) => `- ${c.id}: ${c.description}`)
        .join("\n");

      const prompt = `You are a text classifier. Based on the input text, select the most appropriate class from the options below.

Available classes:
${classesList}

Input text:
${text}

If the input is malformed, doesn't make sense, or you cannot determine an appropriate class, provide brief reasoning and then output <ERROR>Short-error-text</ERROR> where Short-error-text explains the issue.

Otherwise, return ONLY the class id, nothing else.`;

      try {
        const response = await fetch(`${baseURL}/chat/completions`, {
          method: "POST",
          headers: {
            Authorization: `Bearer ${env.OPENROUTER_API_KEY}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            model,
            messages: [
              {
                role: "user",
                content: prompt,
              },
            ],
            temperature: 0,
            // not 'none', otherwise it won't classify properly
            reasoning_effort: text.length > 10000 ? "medium" : "low",
            usage: {
              include: true,
            },
          }),
        });

        if (!response.ok) {
          const errorText = await response.text();
          throw classifyHttpError(
            response.status,
            `OpenRouter API error: ${response.status} - ${errorText}`,
            { source: "Text.classify" }
          );
        }

        const result = await response.json();

        if (!result.choices || result.choices.length === 0) {
          throw new NetworkError("No response generated by the model", { source: "Text.classify" });
        }

        const usage = result.usage || {};
        const content = result.choices[0].message?.content?.trim();
        if (!content) {
          throw new LogicError("No content found in the response", { source: "Text.classify" });
        }

        // Check for error pattern
        const errorMatch = content.match(/<ERROR>(.*?)<\/ERROR>/s);
        if (errorMatch) {
          const errorMessage = errorMatch[1].trim();
          throw new LogicError(errorMessage || "LLM reported an error", { source: "Text.classify" });
        }

        debugTextClassify(
          "Classification completed",
          { selectedClass: content },
          "usage",
          usage
        );

        await getContext().createEvent("text_classify", {
          textLength: text.length,
          classCount: classes.length,
          selectedClass: content,
          usage: { cost: usage.cost },
        });

        return { class_id: content };
      } catch (error) {
        // Re-throw if already classified
        if (isClassifiedError(error)) {
          throw error;
        }
        throw classifyGenericError(error instanceof Error ? error : new Error(String(error)), "Text.classify");
      }
    },
  });
}
