import { defineConfig } from "tsup";

export default defineConfig({
  entry: ["src/index.ts"],
  format: ["esm"],
  dts: true,
  clean: true,
  external: [
    "react",
    "react-dom",
    "@radix-ui/react-avatar",
    "@radix-ui/react-collapsible",
    "@radix-ui/react-dropdown-menu",
    "@radix-ui/react-hover-card",
    "@radix-ui/react-progress",
    "@radix-ui/react-scroll-area",
    "@radix-ui/react-select",
    "@radix-ui/react-slot",
    "@radix-ui/react-tooltip",
    "@radix-ui/react-use-controllable-state",
    "lucide-react",
    "class-variance-authority",
    "clsx",
    "tailwind-merge",
    "embla-carousel-react",
    "ai-elements",
    "@ai-sdk/react",
    "react-syntax-highlighter",
    "streamdown",
    "tokenlens",
    "use-stick-to-bottom",
    "@app/proto"
  ],
  treeshake: true,
  splitting: false,
  sourcemap: true,
  minify: false,
});